//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGBT880_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGDR_IGBT_limits
    {
        public string AGDR_IGBT_MRP { get; set; }
        public string IGBT_type { get; set; }
        public string AGDR_type { get; set; }
        public Nullable<double> Approval_limit_R8_MIN { get; set; }
        public Nullable<double> Approval_limit_R8_MAX { get; set; }
        public Nullable<double> Approval_limit_R8_diff_min { get; set; }
        public Nullable<double> Approval_limit_R8_diff_max { get; set; }
        public string R8_comment { get; set; }
        public Nullable<double> Approval_limit_R7_MIN { get; set; }
        public Nullable<double> Approval_limit_R7_MAX { get; set; }
        public Nullable<double> Approval_limit_R7_diff_min { get; set; }
        public Nullable<double> Approval_limit_R7_diff_max { get; set; }
        public string R7_kommentti { get; set; }
        public int limit_id { get; set; }
    }
}
