//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGBT880_DB
{
    using IGBT880_DAL.Interfaces;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public class IGBT880Entities : DbContext, IDbContext
    {
        public IGBT880Entities()
            : base("name=IGBT880Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barcode_read_status> Barcode_read_status { get; set; }
        public virtual DbSet<Results> Results { get; set; }
        public virtual DbSet<AGDR_IGBT_limits> AGDR_IGBT_limits { get; set; }
        public virtual DbSet<Tester_limits> Tester_limits { get; set; }
        public virtual DbSet<User_list> User_list { get; set; }
    }
}
