//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGBT880_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tester_limits
    {
        public double Temperature_limit_min { get; set; }
        public double Temperature_limit_max { get; set; }
        public double Current_limit_min_t1 { get; set; }
        public double Current_limit_min_t2 { get; set; }
        public double t1 { get; set; }
        public double t2 { get; set; }
        public double Trigger_wait_time { get; set; }
        public double DC_trigger_voltage { get; set; }
        public double I_const { get; set; }
        public double up_scale { get; set; }
        public double u_up_offset { get; set; }
        public double low_scale { get; set; }
        public double u_low_offset { get; set; }
        public double par_199_03 { get; set; }
        public double par_199_04 { get; set; }
        public double par_199_05 { get; set; }
        public double par_199_06 { get; set; }
        public double par_199_07 { get; set; }
    }
}
