//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGBT880_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barcode_read_status
    {
        public int TestId { get; set; }
        public string AGDR_IGBT_Barcode { get; set; }
        public string AGDR_Barcode { get; set; }
        public string IGBT_Barcode { get; set; }
        public string SAP_user_ID { get; set; }
        public Nullable<System.DateTime> SAP_file_saving_time { get; set; }
        public string AGDR_IGBT_MRP { get; set; }
        public Nullable<System.DateTime> Last_Modified { get; set; }
        public Nullable<int> Test_Sequency { get; set; }
        public string Status { get; set; }
        public string Approval { get; set; }
        public string Where_used { get; set; }
    }
}
